---
#- name: gather facts only
#  hosts: all
- name: test template
  hosts: application
  gather_facts: no
  remote_user: root
  vars:
  #  ansible_managed: Ansible Managed
  tasks:
    - name: gather facts
      delegate_to: "{{ item }}"
      delegate_facts: yes
      setup:
      loop: "{{ groups['all'] }}"
    - name: deploy template
      template:
        src: hosts.j2
        dest: /etc/local-report.txt
#      when: "'application' in group_names"
        #state: present
