---
- name: test webapp role
  hosts: webserver
  become: yes

  pre_tasks:
    - name: firewall is running
      service:
        name: firewalld
        state: started
        
  roles:
    - webapp

  tasks:

       - name: check webserver
         uri:
           url: http://rhel2/
           status_code: 200
           return_content: yes
         register: reply
       - name: print output  
         debug:
           var: reply.content
        
